"""Add Security and DailyPrice tables

Revision ID: 50535f05a66c
Revises: f07ac5300e5a
Create Date: 2025-07-07 06:54:30.574346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50535f05a66c'
down_revision = 'f07ac5300e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('exchange', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('daily_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'date', name='uq_security_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_prices')
    op.drop_table('securities')
    # ### end Alembic commands ###
