"""Initial migration

Revision ID: b6cef2497658
Revises:
Create Date: 2025-12-14 10:11:31.547037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cef2497658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('time_frame', sa.String(length=20), nullable=False),
    sa.Column('prediction_type', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('actual_outcome', sa.String(length=10), nullable=True),
    sa.Column('rightness_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source')
    op.drop_table('prediction')
    op.drop_table('stock')
    # ### end Alembic commands ###
